# Generated by Django 3.2.9 on 2022-01-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_auto_20220102_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
